$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: iris-endpoint-joshua

model:
  path: ../models
  type: mlflow_model

environment:
  image: mcr.microsoft.com/azureml/mlflow-ubuntu20.04-py38-cpu-inference:latest

instance_type: Standard_E2s_v3
instance_count: 1
