name: iris-mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  # WICHTIG: Numerics über conda (liefert passende native Libs, vermeidet 502 durch fehlende Runtimes)
  - numpy
  - scipy
  - scikit-learn=1.7.2
  - pip
  - pip:
      - mlflow>=2.8
      - cloudpickle
